# Generated by Django 4.0.5 on 2022-06-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0002_todo_owner_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('Work', 'work'), ('Home', 'home'), ('Other', 'other')], default='work', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='date_completed',
            field=models.DateField(null=True),
        ),
    ]
